### ISSUE TITLE
login wird nicht getriggert

### ISSUE THREAD

**Issue by V4M0N0S** [Kuroosh/altV-Gangwars#3]
Hey,

auf der aktuellen Version wird anscheinen der Login nicht getriggert. Getestet mit der 7.3. 

Getriggert werden:

resource/Client/Notification/notify.html
http://resource/Client/Notification/notify.html

resource/Client/UI/main.html
http://resource/Client/UI/main.html

resource/Client/Car/main.html
http://resource/Client/Car/main.html

ui
http://ui/index.html#/home

MFG

**Comment by Kuroosh** [comment]
Hey :) ,

erstmal : vielen dank für's testen :)

ich schau es mir aufjedenfall die tage an und bringe ein fix raus ♥

Gruß
Kuroosh

**Comment by V4M0N0S** [comment]
Grüße,

pull ist offen für missing args. Im debug nichts wichtiges. Meld dich die Tage einfach ;)

**Comment by V4M0N0S** [comment]
Hey, bin bei alt:V zum größten Teil raus, außerdem sind weitaus neuere Versionen released. Lets close.

Beste Grüße
